name: karawan
description: "Smart home application."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  app_ui:
    path: packages/app_ui
  data_provider:
    path: packages/data_provider
  flutter_bloc: ^9.1.1
  formz: ^0.8.0
  path_provider: ^2.1.5
  # auto_size_text: ^3.0.0
  equatable: ^2.0.7
  talker_flutter: ^4.9.3
  talker_bloc_logger: ^4.9.3
  talker: ^4.9.3
  get_it: ^8.2.0

  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  hydrated_bloc: ^10.1.1
  flutter_secure_storage: ^9.2.4
  flutter_screenutil: ^5.9.3
  hugeicons: ^0.0.11
  input_quantity: ^2.5.1
  shared_preferences: ^2.5.3
  fast_cached_network_image: ^1.3.3+5
  flutter_hooks: ^0.21.2
  go_router: ^16.1.0
  carousel_slider_plus: ^7.1.1
  flutter_intro: ^3.4.0
  tutorial_overlay: ^1.1.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  
  turkmen_localization_support: ^0.0.13

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  hive_ce_generator: ^1.9.3
  bloc_lint: ^0.2.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/
  # - assets/svg/
