name: app_ui
description: App UI Component Library.
version: 0.0.3

publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  anim_search_bar: ^2.0.3
  
  carousel_slider_plus: ^7.1.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.11.0
  flutter_hooks: ^0.21.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  hive_ce_flutter: ^2.3.1
  input_quantity: ^2.5.1
  # skeletonizer: ^2.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.6.0


flutter:
  assets:
    - assets/
    - assets/svg/
    - assets/nav_bar/
    - assets/images/
    - assets/images/brands/
    - assets/images/meals/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

flutter_gen:
  assets:
    enabled: true
    outputs:
      directory_path_enabled: true
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80 

  integrations:
    image: true
    flutter_svg: true