name: app_ui
description: App UI Component Library.
version: 0.0.3

publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider_plus: ^7.1.1
  flutter:
    sdk: flutter
  flutter_boxicons: ^3.2.0
  flutter_gen: ^5.11.0
  flutter_hooks: ^0.21.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  skeletonizer: ^2.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.6.0


flutter:
  assets:
    - assets/
    - assets/svg/
    - assets/nav_bar/
    - assets/images/
    - assets/images/brands/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Black.otf
  #         weight: 900
  #       - asset: assets/fonts/Inter-ExtraBold.otf
  #         weight: 800
  #       - asset: assets/fonts/Inter-Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/Inter-SemiBold.otf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/Inter-Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Light-BETA.otf
  #         weight: 300
  #       - asset: assets/fonts/Inter-ExtraLight-BETA.otf
  #         weight: 200
  #       - asset: assets/fonts/Inter-Thin-BETA.otf
  #         weight: 100

flutter_gen:
  assets:
    enabled: true
    outputs:
      directory_path_enabled: true
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80 

  integrations:
    image: true
    flutter_svg: true