name: data_provider
description: "A package which handle 3rd layer data from out."
version: 0.2.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  talker_dio_logger: ^4.9.3
  talker_flutter: ^4.9.3
  retrofit: ^4.7.1
  json_annotation: ^4.9.0
  internet_connection_checker_plus: ^2.7.2
  flutter_secure_storage: ^9.2.4
  hive_ce_flutter: ^2.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.2
